# Generated by Django 3.1.7 on 2021-03-30 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='desc',
            new_name='decs',
        ),
    ]
